### ISSUE TITLE
summary of v20 account forbidden

### ISSUE THREAD

**Issue by bm842** [bm842/Brokers#3]
If i try to access the summary of my v20 account, it fails with HTTP error 403. 

$ curl -v  -H "Content-Type: application/json"  -H "Authorization: Bearer <hidden>"  "https://api-fxpractice.oanda.com/v3/accounts"
-   Trying 198.105.27.154...
- Connected to api-fxpractice.oanda.com (198.105.27.154) port 443 (#0)
- TLS 1.2 connection using TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
- Server certificate: api-fxpractice.oanda.com
- Server certificate: thawte DV SSL CA - G2
- Server certificate: thawte Primary Root CA
  > GET /v3/accounts HTTP/1.1
  > Host: api-fxpractice.oanda.com
  > User-Agent: curl/7.49.1
  > Accept: _/_
  > Content-Type: application/json
  > Authorization: Bearer <hidden>
  > 
  < HTTP/1.1 200 OK
  < Access-Control-Allow-Headers: Authorization, Content-Type, Accept-Datetime-Format, OANDA-Agent
  < Access-Control-Allow-Methods: PUT, PATCH, POST, GET, OPTIONS, DELETE
  < Access-Control-Allow-Origin: *
  < Connection: keep-alive
  < Content-Length: 52
  < Content-Type: application/json; charset=UTF-8
  < 
- Connection #0 to host api-fxpractice.oanda.com left intact
  {"accounts":[{"id":"xxx","tags":[]}]}

$ curl -v  -H "Content-Type: application/json"  -H "Authorization: Bearer <hidden>"  "https://api-fxpractice.oanda.com/v3/accounts/xxx/summary"
-   Trying 198.105.27.154...
- Connected to api-fxpractice.oanda.com (198.105.27.154) port 443 (#0)
- TLS 1.2 connection using TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
- Server certificate: api-fxpractice.oanda.com
- Server certificate: thawte DV SSL CA - G2
- Server certificate: thawte Primary Root CA
  > GET /v3/accounts/101-001-129737-001/summary HTTP/1.1
  > Host: api-fxpractice.oanda.com
  > User-Agent: curl/7.49.1
  > Accept: _/_
  > Content-Type: application/json
  > Authorization: Bearer <hidden>
  > 
  < HTTP/1.1 403 Forbidden
  < Access-Control-Allow-Headers: Authorization, Content-Type, Accept-Datetime-Format, OANDA-Agent
  < Access-Control-Allow-Methods: PUT, PATCH, POST, GET, OPTIONS, DELETE
  < Access-Control-Allow-Origin: *
  < Content-Length: 0
  < 
- Connection #0 to host api-fxpractice.oanda.com left intact
  $

**Comment by bm842** [comment]
You received a 403 because the token being used in this v20 REST call is from the legacy REST API.

You needs to revoke this token and then generate a new one, and this will work with both the legacy and v20 REST calls.

**Comment by sircambridge** [comment]
ah. this is very confusing, as they state that tokens work for both the legacy api and v20. thanks
